# Site settings
title: Eagle
email: cn.haochen@gmail.com
description: Eagle - Secure Hadoop in Real Time

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://goeagle.io" # the base hostname & protocol for your site
# twitter_username: eagle
# github_username:  eagle

############################################################################ 
# doc_baseurl: defined for base url of the doc page generated for versions
# latest_version: the version number of latest release
# retained_version_limit: the limitation of versions shown in dropdown list
# retained_versions: an array contains versions
# 
# notice: the port number following the version number is temporary just for demo
doc_baseurl: "http://localhost:4001/projects/incubator-eagle/eagle-release-"
latest_version: "2.1"
retained_version_limit: 3
retained_versions: ["1.8:4002", "1.7:4003", "1.6:4004", "1.5", "1.4"]

# host ip only for demo
demo_host: 10.65.251.222

# Build settings
markdown: kramdown
permalink: date

sass:
  sass_dir: _sass

left_nav_links:
  home:
    - title: "Overview & Architecture"
      url: /index.html
    - title: "What's Eagle"
      url: /description.html
    - title: "Eagle's Ecosystem"
      url: /ecosystem.html
    - title: "Who Uses Eagle"
      url: /customers.html
  development:
    - title: "Development Quick Guide"
      url: /development.html
    - title: "Setup Development Env"
      url: /dev-env-setup.html
    - title: "How to Test"
      url: /how-to-test.html
    - title: "How to Contribute"
      url: /how-to-contribute.html
    - title: "How to Write Document"
      url: /how-to-write-doc.html
    - title: "How to Build Binary Package"
      url: /how-to-build-bin-pkg.html
    - title: "How to make a Release"
      url: /how-to-release.html
    - title: "Create alert notification Plugin"
      url: /create-alert-notification-plugin.html

#documentations:
#  - category: Getting Started
#    links:
#     - title: Introduction
#        url: /docs/index.html
#      - title: Quick Start
#        url: /docs/quick-start.html
#      - title: Terminology
#        url: /docs/terminology.html
#      - title: Ecosystem
#        url: /docs/ecosystem.html
#      - title: Community
#        url: /docs/community.html
#      - title: FAQ
#        url: /docs/FAQ.html
#  - category: Installation
#    links:
#      - title: Deploy Eagle in Sandbox
#        url: /docs/deployment-in-sandbox.html
#      - title: Work with configured Sandbox
#        url: /docs/work-with-configured-sandbox.html
#      - title: Deploy Eagle in the Production
#        url: /docs/deployment-in-production.html
#      - title: Stream Log Data into Kafka
#        url: /docs/import-hdfs-auditLog.html
#      - title: Install Eagle Ambari Plugin
#        url: /docs/ambari-plugin-install.html
#      - title: Configuration
#        url: /docs/configuration.html
#  - category: Tutorial
#    links: 
#      - title: Site Management Tutorial
#        url: /docs/tutorial/setup.html
#      - title: Eagle Policy Tutorial
#        url: /docs/tutorial/policy.html
#      - title: User Profile Tutorial
#        url: /docs/tutorial/userprofile.html
#      - title: Data Classification Tutorial
#        url: /docs/tutorial/classification.html
#      - title: Eagle LDAP Tutorial
#        url: /docs/tutorial/ldap.html
#  - category: Advanced
#    links: 
#      - title: Eagle Architecture Highlights
#        url: /docs/architecture-highlights.html
#      - title: Policy API Design
#        url: /docs/policy-api.html
#      - title: User Profile Machine Learning
#        url: /docs/user-profile-ml.html
#